name       : gob2
version    : 2.0.20
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gob2/2.0/gob2-2.0.20.tar.xz : 5fe5d7990fd65b0d4b617ba894408ebaa6df453f2781c15a1cfdf2956c0c5428
license    : GPL-2.0
component  : programming.tools
summary    : GObject Builder
description: |
    Very simple preprocessor for making GObject objects with inline C code so that generated files are not editted
builddeps  :
    - gcc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
patterns   :
    - /usr/share/aclocal